branch-defaults:
  activitytag-join-table:
    environment: Mytraveltemplateapi-env
environment-defaults:
  Mytraveltemplateapi-env:
    branch: null
    repository: null
global:
  application_name: mytraveltemplateapi
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Tomcat 8.5 with Java
    8 running on 64bit Amazon Linux/3.0.1
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
